{
	"version": 1588050232,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/background1-sheet0.png",
		"images/mulai-sheet0.png",
		"images/keluar-sheet0.png",
		"images/bgdesain-sheet0.png",
		"images/gajahgambar-sheet0.png",
		"images/gajah-sheet0.png",
		"images/harimau-sheet0.png",
		"images/jerapah-sheet0.png",
		"images/kasuari-sheet0.png",
		"images/rusa-sheet0.png",
		"images/singa-sheet0.png",
		"images/rusagambar-sheet0.png",
		"images/singagambar-sheet0.png",
		"images/jerapahgambar-sheet0.png",
		"images/harimaugambar-sheet0.png",
		"images/bgdesain2-sheet0.png",
		"images/angka1-sheet0.png",
		"images/angka2-sheet0.png",
		"images/angka3-sheet0.png",
		"images/angka4-sheet0.png",
		"images/angka5-sheet0.png",
		"images/angka6-sheet0.png",
		"images/gajahgambars2-sheet0.png",
		"images/harimaugambars2-sheet0.png",
		"images/jerapahgambars2-sheet0.png",
		"images/rusagambars2-sheet0.png",
		"images/bgpembuat-sheet0.png",
		"images/kembali-sheet0.png",
		"images/pembuat-sheet0.png",
		"media/in the jungle, the mighty jungle.ogg",
		"media/cat.ogg",
		"media/kitten.ogg",
		"media/apakah nama hewan ini-.ogg",
		"media/berapa banyak hewan ini-.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"penumbra.png"
	]
}